version: '3'


networks:
  inception:
    name: inception
    driver: bridge
    
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
    - inception
    build: ./requirements/mariadb
    env_file: 
    - .env
    volumes:
    - mariadb_data:/var/lib/mysql
    restart: always
    expose:
    - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    networks:
    - inception
    build: ./requirements/wordpress
    env_file: 
    - .env
    volumes:
    - wordpress_data:/var/www/html
    restart: always
    expose: 
    - "9000"
  
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
    - inception
    build: ./requirements/nginx
    volumes:
    - wordpress_data:/var/www/html
    restart: always
    ports: 
    - "443:443"


volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: "/home/vpeinado/data/mariadb"
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: "/home/vpeinado/data/wordpress"
      o: bind
